docs: added colab templates
exdevutem/mi-utem pull request #1
Opened 2021-05-02 06:58 UTC by Ballena0

Este pr no tiene template, es el pr para implementarlos 🤔

2021-05-02 20:52 UTC, mapacheverdugo requested changes
Dejar todo lo traducible en español, aunque se pueden ocupar palabras como `bug` o `feature`, o `checklist`. Pero `Description` es muy traducible, por dar ejemplo

❤️

2021-05-02 20:52 UTC, mapacheverdugo commented on docs/pull_request_template.md
> +- [ ] Mis cambios no generan nuevas alertas(Warnings)
Falta su espacio entre `alertas` y `(Warnings)`

2021-05-02 20:52 UTC, mapacheverdugo commented on docs/pull_request_template.md
> +# Description
En español mejor

2021-05-02 20:52 UTC, mapacheverdugo commented on docs/pull_request_template.md
> +## Type of change
🇪🇸

2021-05-02 20:52 UTC, mapacheverdugo commented on docs/pull_request_template.md
> +- [ ] Bug fix
En 🇪🇸 : Correción de bug

2021-05-02 20:52 UTC, mapacheverdugo commented on docs/pull_request_template.md
> +- [ ] New feature
🇪🇸 : `Nueva funcionalidad` o `Nueva feature`

2021-05-02 20:52 UTC, mapacheverdugo commented on docs/issue_template.md
> +# Resources
🇪🇸

2021-05-02 20:52 UTC, mapacheverdugo commented on docs/issue_template.md
> +# Description
🇪🇸

2021-05-02 20:52 UTC, mapacheverdugo commented on docs/issue_template.md
> +## Type of change
🇪🇸  en español

2021-05-02 20:52 UTC, mapacheverdugo commented on docs/issue_template.md
> +- [ ] Bug fix
🇪🇸  igual que el otro archivo

2021-05-02 20:52 UTC, mapacheverdugo commented on docs/issue_template.md
> +- [ ] New feature
🇪🇸. igual que el otro archivo

2021-05-03 16:12 UTC, Ballena0 commented on docs/pull_request_template.md
> +- [ ] Mis cambios no generan nuevas alertas(Warnings)
Corregidos todos estos cambios, se podrían haber hecho menos comentarios individuales pero esta bien.

2021-05-03 17:18 UTC, Javendanon requested changes
Nice 🎉  tengo un par de sugerencias para discutir btw 👀

2021-05-03 17:18 UTC, Javendanon commented on docs/issue_template.md
> +
Añadir límite de LOC (lines of code) para cada PR, creo que 1000 its ok

2021-05-03 17:18 UTC, Javendanon commented on docs/issue_template.md
> +
maybe improvements? se podria tirar como correción de error pero si es sólo una mejora quizá estaría bueno considerarlo aparte @mapacheverdugo que opinai?

2021-05-03 18:19 UTC, Ballena0 commented on docs/issue_template.md
> +
Cool, también creo 1k está bien, por lo general los archivos están con <500 LOC

2021-05-03 18:20 UTC, Ballena0 commented on docs/issue_template.md
> +
Esto también incluiría mejorar el "performance" de algún bloque de código?

2021-05-04 01:31 UTC, Javendanon commented on docs/issue_template.md
> +
Si, es justamente para todo lo que involucre performance e improvements

2021-05-04 01:31 UTC, Javendanon approved these changes
💯

2021-05-08 21:38 UTC, closed without merging