Asignatura Controller
exdevutem/mi-utem pull request #27
Opened 2023-04-18 23:18 UTC by PollitoMayo

# Descripción

Saco este PR principalmente para permitir que la clase AsignaturaScreen pueda ser llamada desde un Get.toNamed sin necesidad de pasarle la asignatura como requisito.

Para esto añadí un controlador que mantiene cargada la lista de asignaturas y además guarda la asignatura seleccionada. De esta forma, la consulta para el listado de asignaturas se realiza una sola vez (cuando se inicia el controlador) y se mantiene guardada junto con la asignación de la última asignatura seleccionada. Esto último permite que se pueda acceder al detalle de la asignatura desde cualquier lado.

Con esto, elimino el FutureBuilder ya que se cambia por un observable para definir qué widget se muestra (loading, error o contenido).

## Tipo de cambio

- [ ] Corrección de error.
- [x] Nueva funcionalidad .
- [ ] Breaking change (cambio que puede romper la aplicación).
- [ ] Documentación.
- [x] Mejora de código existente (performance y/o estilo del código y/o otra mejora)

# Checklist:

- [x] He practicado una revisión de mi propio código.
- [ ] He comentado mi código, sobretodo en las partes que pueden resultar difíciles de entender.
- [x] Mis cambios no generan nuevas alertas (Warnings).
- [x] Este pull request contiene <1000 lineas de código (LOC).

2023-04-18 23:26 UTC, RafaelMoralesV commented on lib/screens/asignaturas_screen.dart
> +      ),*/
Borra todo este código comentado!

2023-04-18 23:31 UTC, PollitoMayo commented on lib/screens/asignaturas_screen.dart
> +      ),*/
Borrado ✌️

2023-04-19 17:04 UTC, RafaelMoralesV approved these changes

2023-04-19 17:04 UTC, RafaelMoralesV commented on lib/screens/asignaturas_screen.dart
> +    controller.getAsignaturas();
sigue necesitando ser una función asíncrona?

2023-04-19 17:04 UTC, RafaelMoralesV commented on lib/screens/asignaturas_screen.dart
> +    controller.getAsignaturas();
ya, tuve leyendo y si sigue necesitando ser asincrona, ya que el widget PullToRefresh toma una función que retorne un futuro para el miembro onRefresh

Hay un par de formas de hacerlo más bonito pero creo que no viene al caso, que está bien así como está ksjdks

2023-04-20 02:07 UTC, mapacheverdugo requested changes
Preferiría si dejamos el controller `AsignaturasController` (lista) separado del controller de `AsignaturaController` (individual), porque el endpoint de obtener el listado obtiene solo algunos datos básicos de la asignatura, y `AsignaturaScreen` también llama al endpoint de las notas (y en un futuro podría llamar al de obtener estudiantes), por lo que me hace sentido que sean por separado

Además así facilitaría para cuando dejemos que el controller individual se pueda llamar solo con ID

2023-04-20 02:07 UTC, mapacheverdugo commented on CHANGELOG.md
> +- Se añade controlador para Asignaturas
Sé que no tiene que ver con tu PR, pero el release anterior no se estampó en el changelog, puedes ponerlo como `## [2.11.4] - 2023-04-13Z` y agregar tu cambio desde 0 a `## [Unreleased]`?

2023-04-20 02:33 UTC, mapacheverdugo commented on lib/controllers/asignatura_controller.dart
> +  void getAsignaturas([bool refresh = false]) async {
Podemos cambiarlo a `{bool refresh = false}` para que quede named?

2023-04-26 01:30 UTC, PollitoMayo commented on lib/controllers/asignatura_controller.dart
> +  void getAsignaturas([bool refresh = false]) async {
Oh, si si, yo igual lo preferiría de esa forma. Lo mantuve como estaba para dejar los cambios mínimos posibles, pero ya lo cambio

2023-04-26 02:12 UTC, mapacheverdugo commented on lib/controllers/asignatura_controller.dart
> +  void getAsignaturas([bool refresh = false]) async {
sí, mi culpa, taba chiquito y no sabía lo que hacía

2023-07-20 21:00 UTC, mapacheverdugo approved these changes

2023-07-20 21:01 UTC, merged