Adios señora
exdevutem/mi-utem pull request #30
Opened 2023-04-27 02:38 UTC by RafaelMoralesV

# Descripción

Ya era alta hora de que se fuera la dama

## Tipo de cambio

- [x] Breaking change (cambio que puede romper la aplicación).

# Checklist:

- [x] He practicado una revisión de mi propio codigo.
- [x] He comentado mi codigo, sobretodo en las partes que pueden resultar dificiles de entender.
- [x] Mis cambios no generan nuevas alertas (Warnings).
- [x] Este pull request contiene <1000 lineas de codigo (LOC).

2023-04-27 03:08 UTC, mapacheverdugo commented
Piensa en otro 🥚 pa poner

2023-04-27 03:12 UTC, RafaelMoralesV commented
> Piensa en otro 🥚 pa poner 

consigamos una vendida de todos los que salen en el about, y que les reemplace la foto a todos 1 de cada 10 veces

o que les ponga adornos en ciertas fechas, gorritos de navidad por ejemplo, no sé.

2023-04-27 03:13 UTC, RafaelMoralesV commented
me da paja trabajar en el theming de la app, pero sería entrete que cambiara de color a uno de halloween a finales de octubre, o a una paleta navideña en diciembre y así

2023-04-27 03:24 UTC, mapacheverdugo commented
Me gusta lo de las vendidas y el theming, los gorritos es más dificil de programar creo io

2023-04-27 03:24 UTC, mapacheverdugo commented
Y si quizás en vez de vendidas los pasamos por un filtro que los haga a todos chad? Así no necesitamos buscar fotos de nadie

2023-04-27 03:26 UTC, RafaelMoralesV commented
> Y si quizás en vez de vendidas los pasamos por un filtro que los haga a todos chad? Así no necesitamos buscar fotos de nadie

JAJA
Dale, se pensó y se hizo

2023-05-03 01:21 UTC, mapacheverdugo approved these changes
Aprobadito pero puedes ver lo del changelog pls? uwu

2023-05-03 01:21 UTC, mapacheverdugo commented on CHANGELOG.md
> +- Se eliminó el anuncio de 'gestando nuevas funciones'. La señora vivirá siempre en nuestros corazones.
Ya que la Kavita no ha podido hacer el cambio, puedes pegarte la misión?

> Sé que no tiene que ver con tu PR, pero el release anterior no se estampó en el changelog, puedes ponerlo como `## [2.11.4] - 2023-04-13Z` y agregar tu cambio desde 0 a `## [Unreleased]`?

2023-05-03 02:07 UTC, RafaelMoralesV commented on CHANGELOG.md
> +- Se eliminó el anuncio de 'gestando nuevas funciones'. La señora vivirá siempre en nuestros corazones.
Listoco

2023-05-03 15:29 UTC, mapacheverdugo requested changes

2023-05-03 15:29 UTC, mapacheverdugo commented on CHANGELOG.md
> +### Fixed
Dejaste los títulos en blanco, si no se ponen

2023-05-03 15:29 UTC, mapacheverdugo commented on CHANGELOG.md
>  ### Added
Dejaste los títulos en blanco, si no se ponen

2023-05-03 16:03 UTC, RafaelMoralesV commented on CHANGELOG.md
> +### Fixed
meu deus, ya, deja lo cambio

2023-05-03 16:42 UTC, mapacheverdugo approved these changes

2023-05-04 22:52 UTC, PollitoMayo approved these changes
Medapena pero ya cumplió su ciclo, toca jubilarla.

2023-05-05 12:53 UTC, merged