Agregado banner de innova utem
exdevutem/mi-utem pull request #37
Opened 2023-10-07 20:13 UTC by Im-Fran

# Descripción

Por favor incluye una lista de los cambios. 
Por favor incluye contexto y motivación relevantes. 
Si incluyes nuevas dependencias, por favor, haz una lista de las necesarias.

## Tipo de cambio

- [ ] Corrección de error.
- [X] Nueva funcionalidad .
- [ ] Breaking change (cambio que puede romper la aplicación).
- [ ] Documentación.
- [ ] Mejora de codigo existente (performance y/o estilo del codigo y/o otra mejora)

# Checklist:

- [X] He practicado una revisión de mi propio codigo.
- [ ] He comentado mi codigo, sobretodo en las partes que pueden resultar dificiles de entender.
- [X] Mis cambios no generan nuevas alertas (Warnings).
- [ ] Este pull request contiene <1000 lineas de codigo (LOC).

# Recursos

Añade cualquier documentación que facilite la comprensión de la solución.

2023-10-07 20:13 UTC, Im-Fran commented
Hace falta ver si se ve bien en otros dispositivos (android) y distintos tamaños de pantalla, pero creo que está bien 😄

2023-10-09 04:48 UTC, mapacheverdugo requested changes

2023-10-09 04:48 UTC, mapacheverdugo commented on lib/widgets/innova_utem_banner.dart
> +          width: 350,
Por qué estas medidas?

2023-10-09 04:48 UTC, mapacheverdugo commented on lib/widgets/innova_utem_banner.dart
> +              elevation: 5,
Sin `elevation` para seguir el lineamiento de diseño del resto de la app

2023-10-09 04:48 UTC, mapacheverdugo commented on lib/widgets/innova_utem_banner.dart
> +                borderRadius: BorderRadius.circular(10),
Lo mismo acá, sin `shape`/`borderRadius` para que siga los lineamientos del resto de la app

2023-10-09 04:48 UTC, mapacheverdugo commented on lib/widgets/innova_utem_banner.dart
> +                          style: Get.textTheme.bodyLarge!.copyWith(
Este botón de donde sale? Perdón estoy perdido, no fui a la reu :nooooo: También me sirve si response @RafaelMoralesV

2023-10-09 15:03 UTC, RafaelMoralesV commented on lib/widgets/innova_utem_banner.dart
> +              )),
Si atiendes lo que revisa el jorge, te molestaría agregar una coma aquí igual para que se separen los paréntesis? me está pegando el TOC askjdna

2023-10-09 15:04 UTC, RafaelMoralesV commented on lib/widgets/innova_utem_banner.dart
> +                          style: Get.textTheme.bodyLarge!.copyWith(
@mapacheverdugo quedé pillo con la pregunta. A qué te refieres?

2023-10-09 19:17 UTC, mapacheverdugo commented on lib/widgets/innova_utem_banner.dart
> +                          style: Get.textTheme.bodyLarge!.copyWith(
Hay un. botón de "Ver más", les pidieron alguna especie de diseño de donde basarse o como?

2023-10-09 19:18 UTC, Im-Fran commented on lib/widgets/innova_utem_banner.dart
> +              )),
xD

2023-10-09 19:18 UTC, Im-Fran commented
Ahora mismo comenzaré a revisar todo esto :p

2023-10-09 20:27 UTC, Im-Fran commented on lib/widgets/innova_utem_banner.dart
> +                          style: Get.textTheme.bodyLarge!.copyWith(
lo copíe de la página, tipo ahí sale "Postula Aquí" de ese color, le puse uno similar pero como para "Ver Más" cosa de que muestre la paǵina de innova utem

2023-10-09 20:28 UTC, Im-Fran commented on lib/widgets/innova_utem_banner.dart
> +                          style: Get.textTheme.bodyLarge!.copyWith(
yo solo copié el diseño de la pagina misma, las imágenes son la de la tipa pensando y el texto de concurso emprende, el fondo es manual, igual que el botón:

![image](https://github.com/exdevutem/mi-utem/assets/30329003/058cc688-6c37-4aeb-9a94-29a8e6591c74)

Aunque igual podría mantenerlo como botón cuadrado en lugar de redondo

2023-10-09 20:29 UTC, Im-Fran commented on lib/widgets/innova_utem_banner.dart
> +                          style: Get.textTheme.bodyLarge!.copyWith(
(esa es una captura de la página, quizá igual pueda mover a la persona más a la izquierda en la app para que sea similar al de la página

2023-10-09 20:31 UTC, Im-Fran commented on lib/widgets/innova_utem_banner.dart
> +              )),
Listo, arreglé esto tambien xD

2023-10-09 20:31 UTC, Im-Fran commented on lib/widgets/innova_utem_banner.dart
> +              )),
No lo había visto, solo dejé que el copilot rellenara lo demás :rofl:

2023-10-09 20:52 UTC, Im-Fran commented
No se si les funcione la app con el cambio de las dependencias, si funciona genials, así podemos seguir con dependencias actualizadas, si no me avisan y se puede revertir ese commit.

2023-10-10 02:14 UTC, mapacheverdugo commented
No funciona con la actualización de librerías, voy a revertir ese cambio para poder hacer lo de Remote Config

Lo otro que estoy pensando es convertir todo el banner a una imagen única, porque si queremos hacerlo genérico (y esa es la razón del Remote Config) lo mejor sería que fuera una imagen

2023-10-10 02:16 UTC, mapacheverdugo commented
Abriré otra PR basada en esta porque no le supe pushear xd

2023-10-10 02:16 UTC, closed without merging

2023-10-10 15:34 UTC, Im-Fran commented
pero que problemas tuviste con las dependencias? tipo no te dejó ejecutarlas? si es así quizá deberiamos actualizar flutter todos para mantener las ultimas actualizaciones y mejoras