Adaptación al refactor
exdevutem/mi-utem pull request #4
Opened 2022-03-22 14:10 UTC by PollitoMayo

# Descripción

Actualicé un poco la app para que funcione con los nuevos cambios del backend, así que está sujeta a la [PR#2](https://github.com/exdevutem/api-mi-utem/pull/2) de `api-mi-utem`.
Hay más de un detalle que falta debido a cómo se está entregando la información, y quizás también porque mi usuario no es el mejor para probar detalles como las salas en el horario (tengo 2 ramos y son online). A pesar de ello, se intentó dejar todo lo más conectado y útil posible ignorando los _nice to have_ como los colores en el horario.

## Tipo de cambio

- [ ] Corrección de error.
- [ ] Nueva funcionalidad .
- [ ] Breaking change (cambio que puede romper la aplicación).
- [ ] Documentación.
- [ ] Mejora de codigo existente (performance y/o estilo del codigo y/o otra mejora)

# Checklist:

- [ ] He practicado una revisión de mi propio codigo.
- [ ] He comentado mi codigo, sobretodo en las partes que pueden resultar dificiles de entender.
- [ ] Mis cambios no generan nuevas alertas (Warnings).
- [ ] Este pull request contiene <1000 lineas de codigo (LOC).

# Recursos

Añade cualquier documentación que facilite la comprensión de la solución.

2022-03-24 13:56 UTC, mapacheverdugo requested changes
- Cuidado con el modelo `Evaluacion`, ya que ahora el atributo no se llama `etiqueta`, se llama `descripcion` y puede (o no) venir desde el backend. Actualmente no se está parseando en el `fromJson`
- En el header del drawer no se está mostrando el correo, debe ser porque tu modelo Usuario no contempla los dos correos por separado `correoUtem` y `correoPersonal`
- El horario, la primera vez que se carga, muestra un error y luego carga. Falta corregir/agregar el indicador de carga
- Eliminar la sección de asistencia en las asignaturas
- Eliminar el chip "Nuevo" en los docentes de la asignatura y desactivar la función del tap
- El `refreshSesion` de `DioMiUtemClient` no está funcionando, hay que cambiarlo para hacer un login de nuevo, con la ruta del login
- Por fa quita los signos de exclamación del `formKey` que está en el `LoginScreen`

<img width="917" alt="image" src="https://user-images.githubusercontent.com/16374322/159931786-ab7d8bc2-4745-4941-80ef-4ce85d7fb965.png">


Además revisa los comentarios en código que te dejé uwu

2022-03-24 13:56 UTC, mapacheverdugo commented on lib/models/usuario.dart
>    String? correo;
Ahora hay dos correos que devuelve la API, `correoPersonal` y `correoUtem`

2022-03-24 13:56 UTC, mapacheverdugo commented on lib/services/autenticacion_service.dart
> +          prefs.setString('correo', usuario.correo!);
Lo mismo, cuidado que son dos correos ahora, `correoPersonal` y `correoUtem`

2022-03-26 16:10 UTC, mapacheverdugo commented
Bien! Hay varios detalles que ya me funcionan, solo un par detalles más:
- Es posible que la tab de "Estudiantes" de la asignatura solo se esconda cuando `estudiantes` sea null o vacío? Siempre y cuando no implique mucho tiempo de desarrollo
- Puedes cambiar la URL de producción a https://api-mi-utem.herokuapp.com/ y la de debug sacarla desde el .env? (Como lo hacemos en Pawer uwu)
- Revisa como estás obteniendo las notas, el endpoint no es el correcto, puedes guiarte de las rutas del backend o del workspace de Postman que dejé en la PR del backend

https://github.com/exdevutem/mi-utem/blob/8f3e2fc832851df1e28c7e764d093d1d8bdec287/lib/services/asignaturas_service.dart#L57-L60

2022-03-26 19:41 UTC, PollitoMayo commented
@mapacheverdugo listo para revisar de nuevo uwu

2022-03-26 20:11 UTC, mapacheverdugo approved these changes
Listo listo, ta bonita la PR. Muchas gracias Kavita!

2022-03-26 20:12 UTC, merged