patch: reparado carga de notas desde asignatura
exdevutem/mi-utem pull request #41
Opened 2023-10-11 19:09 UTC by Im-Fran

# Descripción

Se arregló que al abrir la calculadora desde las notas de la asignatura, no se mostraban las notas precargadas.

## Tipo de cambio

- [X] Corrección de error.
- [ ] Nueva funcionalidad .
- [ ] Breaking change (cambio que puede romper la aplicación).
- [ ] Documentación.
- [ ] Mejora de codigo existente (performance y/o estilo del codigo y/o otra mejora)

# Checklist:

- [X] He practicado una revisión de mi propio codigo.
- [ ] He comentado mi codigo, sobretodo en las partes que pueden resultar dificiles de entender.
- [X] Mis cambios no generan nuevas alertas (Warnings).
- [X] Este pull request contiene <1000 lineas de codigo (LOC).

2023-10-13 03:34 UTC, mapacheverdugo requested changes
Enviarle el parámetro por argumento a la ruta hace que falle en caso de que abras la calculadora por fuera de una asignaturas (como en el quick menú del inicio por ej). Creo que es más simple si llamas a `controller.loadGrades(grades);` directo antes o después del `Get.toNamed` y borras todo lo relacionado con `arguments`

2023-10-14 11:50 UTC, mapacheverdugo requested changes

2023-10-14 11:50 UTC, mapacheverdugo commented on lib/screens/asignatura_detalle_screen.dart
> +                        if (asignatura != null) {
Lo cambiaría a `asignatura?.grades != null` para comprobar tanto que `asignatura` como `asignatura.grades` sean distinto de null

2023-10-15 23:19 UTC, Im-Fran commented on lib/screens/asignatura_detalle_screen.dart
> +                        if (asignatura != null) {
Suena bien 👍

2023-10-16 13:36 UTC, mapacheverdugo approved these changes

2023-10-16 13:38 UTC, merged