F qrcode
exdevutem/mi-utem pull request #6
Opened 2022-04-26 01:05 UTC by RafaelMoralesV

# Descripción

Componentes y pantallas para los QR de los permisos COVID.

- Agregado listado de 'tarjetas' con vinculos a los QR de los permisos COVID
- Pantalla con el detalle y codigo QR para el permiso COVID

## Dependencias
- qr_flutter

## Tipo de cambio

- [ ] Corrección de error.
- [X ] Nueva funcionalidad .
- [ ] Breaking change (cambio que puede romper la aplicación).
- [ ] Documentación.
- [ ] Mejora de codigo existente (performance y/o estilo del codigo y/o otra mejora)

# Checklist:

- [ ] He practicado una revisión de mi propio codigo.
- [ ] He comentado mi codigo, sobretodo en las partes que pueden resultar dificiles de entender.
- [X] Mis cambios no generan nuevas alertas (Warnings).
- [X] Este pull request contiene <1000 lineas de codigo (LOC).

# Recursos
Imagenes con los cambios desde mi propio perfil.

![image](https://user-images.githubusercontent.com/42483328/165197580-6d8fd750-c94c-455f-8193-e8d34c86e62a.png)

![image](https://user-images.githubusercontent.com/42483328/165197910-a94b4e4f-8a6a-4f4f-9f10-6e70e9039a81.png)

## Cosas que aún quiero cambiar
- Refactorizar un poco algunos componentes
- Utilizar la clase MainTheme en vez colores y tamaños fijos.
- Cambiar la forma estética en que estos componentes cargan
- No pude encontrar como agregar la foto del usuario a la pantalla de detalles del permiso, se aceptan sugerencias

2022-04-26 04:44 UTC, mapacheverdugo requested changes
Eso es lo que encontré de momento, en general se ve de pana, solo te queda echarle un ojo a los comentarios y empezar a conectar los textos con la info real uwu

2022-04-26 04:44 UTC, mapacheverdugo commented on lib/services/permisos_covid_service.dart
> +    String uri = "/permisos";
La ruta debería ser `/v1/permisos` como la de los otros services

2022-04-26 04:44 UTC, mapacheverdugo commented on lib/models/permiso_covid.dart
> +  static List<PermisoCovid> fromJsonList(List<Map<String, dynamic>> json) {
Tengo una excepción si lo dejas con el tipo `List<Map<String, dynamic>> json`, se soluciona si lo cambias a `dynamic json`

2022-04-26 04:44 UTC, mapacheverdugo commented on lib/models/permiso_covid.dart
> +    List<PermisoCovid> lista = [];
Quizás falta la comprobación de si la lista es `null` como en los otros modelos
```suggestion
    if (json == null) {
      return [];
    }
    List<PermisoCovid> lista = [];
```

2022-04-26 04:44 UTC, mapacheverdugo commented on lib/widgets/qr_codes.dart
> +                return ListView.builder(
Cuando haces un ListView tienes que poner sí o sí el `itemCount` para indicarle cuántos ítems tendrá la lista, además falta establecer que la lista será horizontal para que el scroll quede bien, además de un padding para que quede alineado con los botones de abajo

```suggestion
                return ListView.builder(
                  scrollDirection: Axis.horizontal,
                  padding: EdgeInsets.symmetric(horizontal: 20),
                  itemCount: snapshot.data.length,
                  itemBuilder: (context, index) =>
                        QRCard(permiso: snapshot.data[index],
                  ),
                );
                
```

2022-04-26 04:44 UTC, mapacheverdugo commented on lib/widgets/qr_codes.dart
> +                Text(
Este debería ser un botón, pero como aún no está la pantalla con todos los permisos, quizás podríamos comentarlo mientras tanto

2022-04-26 04:44 UTC, mapacheverdugo commented on lib/screens/permiso_covid_screen.dart
> +              "https://static.wikia.nocookie.net/memes-pedia/images/4/4f/Gigachad.jpg/revision/latest?cb=20201122221724&path-prefix=es",
lol

2022-04-26 04:44 UTC, mapacheverdugo commented on lib/screens/permiso_covid_screen.dart
> +                    data: "https://www.youtube.com/watch?v=OcJQ-sOK5O8",
loln't

2022-04-26 04:44 UTC, mapacheverdugo commented on lib/screens/permiso_covid_screen.dart
> +          Row(
Quizás sea bueno revisar si los valores son null, si ambos son null, omitir toda la `Row`, si solo uno es null, omitir solo ese elemento de la `Row`

2022-04-26 04:44 UTC, mapacheverdugo commented on lib/widgets/qr_codes.dart
> +                  return const CircularProgressIndicator();
Es mejor que uses `LoadingIndicator` que es un `Widget` custom hecho para unificar todos los cargando que hay en la app

2022-04-26 04:44 UTC, mapacheverdugo commented on lib/widgets/qr_codes.dart
> +class QRCard extends StatelessWidget {
Creo que es bueno separar esto en otro archivo dentro de `/widgets` y creo que quedaría mejor un nombre tipo `PermisoCard` para la clase

2022-04-26 04:44 UTC, mapacheverdugo commented on lib/widgets/qr_codes.dart
> +class QRCodes extends StatefulWidget {
Un mejor nombre para la clase sería `PermisosListView` o `PermisosCarrousel` para mantener la línea de "Permiso" y no usar a veces "Permiso" y otras "QR"

2022-04-26 04:44 UTC, mapacheverdugo commented on lib/widgets/qr_codes.dart
> +  late Future<List<PermisoCovid>> permisos;
Mejor usar el nombre `_permisosFuture` para no confundir que no son realmente los permisos como tal, si no el `Future` de los permisos

2022-04-26 04:44 UTC, mapacheverdugo commented on lib/screens/permiso_covid_screen.dart
> +  const PermisoCovidScreen({Key? key}) : super(key: key);
Aquí tendrías que recibir el `PermisoCovid` como `required this.permiso` parecido a como lo haces en `QRCard`, y luego llamarlo en la navegación como Get.to(PermisoCovidScreen(permiso: permiso))

2022-04-26 04:56 UTC, RafaelMoralesV commented
Ahh creo que te cagué feito
Hay varios cambios que ya tenía listos, que no tenía pusheados
Mil perdones! :( Ojalá no hayas gastado mucho tiempo en revisarlo te debo un chocolate si fue así

2022-04-27 00:52 UTC, mapacheverdugo requested changes
Ya, ahí revisé de nuevo

2022-04-27 00:52 UTC, mapacheverdugo commented on lib/screens/permiso_covid_screen.dart
> +  final String id = Get.arguments['id'];
En vez de usar argumentos para pasar entre pantallas, yo prefiero usar los constructores de las propias clases ya que es menos propenso a errores (como que después alguien más llame a la screen en otro lado y se le olvide mandar el argumento por ej.)

2022-04-27 00:52 UTC, mapacheverdugo commented on lib/screens/permiso_covid_screen.dart
> +              return const CircularProgressIndicator();
Cambiar por un `LoadingIndicator`, idealmente en un Center dentro de un Expanded para que quede centrado en la pantalla

2022-04-27 00:52 UTC, mapacheverdugo commented on lib/services/permisos_covid_service.dart
> +  static Future<dynamic> getDetallesPermiso(String id) async {
Acá no debería devolver un `Future<PermisoCovid>` en vez de un `dynamic`?

2022-04-27 00:52 UTC, mapacheverdugo commented on lib/models/permiso_covid.dart
> +
Acá falta el `String? codigoQr` y quizás un `Usuario? usuario`

2022-04-27 00:52 UTC, mapacheverdugo commented on lib/models/permiso_covid.dart
> +  String? fechaSolicitud;
La fecha debería ser `DateTime` en vez de `String` y lo parseas como `DateTime.tryParse(json["fechaSolicitud"])`

2022-04-27 01:20 UTC, RafaelMoralesV commented on lib/screens/permiso_covid_screen.dart
> +              return const CircularProgressIndicator();
Yes yes, lo siguiente que quiero arreglar es la estetica de las cargas

2022-04-27 01:21 UTC, RafaelMoralesV commented on lib/services/permisos_covid_service.dart
> +  static Future<dynamic> getDetallesPermiso(String id) async {
No estaba del todo seguro en el momento porque pensé que no devolvían estrictamente lo mismo, así que opté por un dynamic por mientras
Voy a pagar la deuda técnica en breve, don't worry

2022-04-27 01:22 UTC, RafaelMoralesV commented on lib/models/permiso_covid.dart
> +  String? fechaSolicitud;
Will do!

2022-04-27 01:36 UTC, RafaelMoralesV commented on lib/models/permiso_covid.dart
> +    List<PermisoCovid> lista = [];
No estoy seguro si es necesario. La única forma que se me ocurre que llegue a ser null es que falle la petición, pero se supone que 'algo' atrapa esa condición antes siempre, no?

2022-04-27 01:43 UTC, RafaelMoralesV commented on lib/widgets/qr_codes.dart
> +class QRCodes extends StatefulWidget {
Estrictamente hablando este componente se encarga de una 'sección' dentro de la pantalla principal. Creo que me gusta más llamarlo como tal, y dejarlo como PermisosCovidSection.

2022-04-27 03:17 UTC, RafaelMoralesV commented on lib/services/permisos_covid_service.dart
> +  static Future<dynamic> getDetallesPermiso(String id) async {
Casi que me gustaria armar un segundo modelo solo por lo ligeramente distintas que son wajsajaj
De todas formas, ya pasó de dynamic a PermisoCovid.

2022-04-27 03:18 UTC, RafaelMoralesV commented on lib/models/permiso_covid.dart
> +
No pude hacer funcionar un tipo Usuario? usuario.
Añadía un poco más de complejidad de lo que realmente era necesario.

2022-04-27 03:22 UTC, RafaelMoralesV commented
Hay dos cositas que me gustarían cambiar

1. Que la carga del detalle de la pantalla use el PermisoCovid que le entrega en el inicio, que no contiene el QR, para mostrar todos los detalles importantes mientras que encuentra el codigo QR como tal
2. Que en las tarjetas de los permisos el texto se alinee al centro. No estoy seguro de como quedará, pero siento que ahora mismo hay mucho espacio en blanco entre el motivo y el boton cuando no existe un campus.

2022-04-27 17:49 UTC, mapacheverdugo commented on lib/models/permiso_covid.dart
> +    List<PermisoCovid> lista = [];
Tru, lo marco como resuelto

2022-04-28 16:07 UTC, mapacheverdugo approved these changes
Ahora lo veo mucho mejor, dejo mi sipoapruebo, hay algo más que quieras cambiar en esta PR?

2022-04-28 16:08 UTC, RafaelMoralesV commented
> Ahora lo veo mucho mejor, dejo mi sipoapruebo, hay algo más que quieras cambiar en esta PR?

Puta puros cambios estéticos la verdad
Pero supongo que es mejor armar otra PR para eso, y que los permisos funcionen cuanto antes.

2022-05-02 23:42 UTC, PollitoMayo approved these changes
Una semana tarde, pero se ve de pana 👍

2022-05-05 14:57 UTC, mapacheverdugo requested changes
@RafaelMoralesV iba a mergear pero te faltaron los cambios del `CHANGELOG.md`, tienes que anotar ahí los cambios que hiciste uwu

2022-05-06 01:26 UTC, RafaelMoralesV commented
> @RafaelMoralesV iba a mergear pero te faltaron los cambios del `CHANGELOG.md`, tienes que anotar ahí los cambios que hiciste uwu

@mapacheverdugo  Hice el cambio que pediste, pero no estoy seguro si está bien (?

2022-05-06 03:55 UTC, mapacheverdugo commented
Ta bien 👍🏻

2022-05-06 03:55 UTC, mapacheverdugo commented
Ah, te agregué como collab directo al repo para que no tengas que hacer fork para armar PR y puedas hacerlo a partir de una branch no más

2022-05-06 03:55 UTC, mapacheverdugo approved these changes

2022-05-06 03:56 UTC, merged